#include <err.h>
#include <sndio.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "midi.h"

/* Wishlist:
 * - User can map any CC number to arbitrary string output */

static void ccs(char[CC_LIMIT][3]);
static void repl(Repl *);
static void parseArgs(Repl *, int, char **);
static void waitForIO(Repl *);
static void readMidi(Repl *);
static void parseCc(Repl *, Cc, uint8_t);
static void parseBend(uint8_t, uint8_t);
static void parseMidi(Repl *, int);
static void readStdin(Repl *);
static void freeRepl(Repl *);

static void ccs(char c[CC_LIMIT][3]) {
  int i = 0;
  for (; i < CC_LIMIT ; i++) {
    if (i == CC_VOL) { strcpy(c[i], "v"); }
    else             { strcpy(c[i], "");  } 
  }
}

static void repl(Repl *r) {
  r->mio                       = mio_open(MIO_PORTANY, MIO_IN, true);
  if (r->mio == NULL) { errx(1, "Error opening MIDI input %s", MIO_PORTANY); }
  r->chan                      = 0;
  r->nfds                      = 1 + mio_nfds(r->mio);
  r->pollFds                   = calloc(r->nfds, sizeof(*r->pollFds));
  r->pollFds[STDIN_IDX].fd     = STDIN_FILENO;
  r->pollFds[STDIN_IDX].events = POLLIN;
  r->inSysex                   = false;
  ccs(r->ccs);
  r->isRunning                 = true;
}

static void parseArgs(Repl *r, int argc, char **argv) {
  int i = 1; /* ignore program name */
  for (; i < argc ; i++) {
    if (strcmp(argv[i], "-chan") == 0) {
      i++;
      r->chan = atoi(argv[i]);
      if (r->chan < 1 || r->chan > 16) {
        errx(1, "MIDI channel must be between 1 and 16, got %d", r->chan);
      }
      r->chan--;
    } else {
      errx(1, "Unknown argument %s", argv[i]);
    }
  }
}

static void waitForIO(Repl *r) {
  int nfds = 0;
  /* No need to reset this every loop, but recommended */
  mio_pollfd(r->mio, &r->pollFds[MIDI_IDX], POLLIN);
  nfds = poll(r->pollFds, r->nfds, -1);
  if (nfds < 1) { errx(1, "Polling failure in main REPL"); }
}

static void readMidi(Repl *r) {
  int bytesRead = 0;
  if (!(r->pollFds[MIDI_IDX].revents & POLLIN)) { return; }
  bytesRead = mio_read(r->mio, r->midi, MIDI_LIMIT);
  parseMidi(r, bytesRead);
  fflush(stdout);
}

static void parseCc(Repl *r, Cc b2, uint8_t b3) {
  char *s = r->ccs[b2 & (CC_LIMIT - 1)];
  if ((strcmp(s, "") == 0)) { return; }
  switch (b2) {
    case CC_VOL:
      printf("%s%.3f\n", s, (float)b3/(float)(CC_LIMIT - 1));
      break;
    default:
      printf("%s%d\n", s, b3);
  }
}

static void parseBend(uint8_t b2, uint8_t b3) {
  uint16_t x = (b3 << 7) | b2;
  float f    = (float)x / (float)((1 << 14) - 1);
  f         *= 2.0f;
  f         -= 1.0f;
  printf("b%.3f\n", f);
}

static void parseMidi(Repl *r, int bytesRead) {
  uint8_t b  = 0;
  uint8_t b2 = 0;
  uint8_t b3 = 0;
  int i      = 0;
  for (; i < bytesRead ; i++) {
    b = r->midi[i];
    if (r->inSysex) {
      if (b == SYSEX_END) { r->inSysex = false; }
      continue;
    }
    switch (GET_EVENT(b)) {
      case NOTE_ON:
        if (GET_CHAN(b) != r->chan) { i += 2; break; }
        b2 = r->midi[++i];
        b3 = r->midi[++i];
        printf("n%d %d\n", b2, b3);
        break;
      case NOTE_OFF:
        if (GET_CHAN(b) != r->chan) { i += 2; break; }
        b2 = r->midi[++i];
        b3 = r->midi[++i];
        printf("o%d %d\n", b2, b3);
        break;
      case CC:
        if (GET_CHAN(b) != r->chan) { i += 2; break; }
        b2 = r->midi[++i];
        b3 = r->midi[++i];
        parseCc(r, b2, b3);
        break;
      case PITCH_BEND:
        if (GET_CHAN(b) != r->chan) { i += 2; break; }
        b2 = r->midi[++i];
        b3 = r->midi[++i];
        parseBend(b2, b3);
        break;
      case CHAN_AFTERTOUCH:
        if (GET_CHAN(b) != r->chan) { i += 1; break; }
        b2 = r->midi[++i];
        printf("t%d\n", b2);
        break;
      case POLY_AFTERTOUCH:
        if (GET_CHAN(b) != r->chan) { i += 2; break; }
        b2 = r->midi[++i];
        b3 = r->midi[++i];
        printf("t%d %d\n", b2, b3);
        break;
      case PROGRAM_CHANGE:
        i += 1;
        break;
      case MTC:
        i += 1;
        break;
      case SONG_POSITION:
        i += 2;
        break;
      case SONG_SELECT:
        i += 1;
        break;
      case SYSEX_START:
        r->inSysex = true;
        break;
      default:
        return;
    }
  }
}

static void readStdin(Repl *r) {
  /* There is no reason to read stdin as of yet, but this will allow dynamic
   * MIDI mappings to be generated by the user at runtime. */
  if (!(r->pollFds[STDIN_IDX].revents & POLLIN)) { return; }
  if (fgets(r->input, REPL_LIMIT, stdin) == NULL) { 
    r->isRunning = false;
    return;
  }
  printf("%s", r->input);
  fflush(stdout);
}

static void freeRepl(Repl *r) {
  free(r->pollFds);
}

int main(int argc, char **argv) {
  Repl r = {0};
  repl(&r);
  parseArgs(&r, argc, argv);
  warnx("Listening on MIDI channel %d", r.chan +1);
  while (r.isRunning) {
    waitForIO(&r);
    readMidi(&r);
    readStdin(&r);
  }
  freeRepl(&r);
  return 0;
}
