(import boar-param boar-mixer boar-slice srfi-4 srfi-18 (chicken string))

(define mix (mixer-new-from-lengths 2 2 4))
(mixer-new-master-volume-set!   mix     111.0)
(mixer-new-master-balance-set!  mix 0   222.0)
(mixer-new-master-balance-set!  mix 1   333.0)
(mixer-new-channel-volume-set!  mix 0   444.0)
(mixer-new-channel-volume-set!  mix 1   777.0)
(mixer-new-channel-balance-set! mix 0 0 555.0)
(mixer-new-channel-balance-set! mix 0 1 666.0)
(mixer-new-channel-balance-set! mix 1 0 888.0)
(mixer-new-channel-balance-set! mix 1 1 999.0)
(params-new (mixer-new-params mix))
(define output (make-u8vector 16 0 #t #f))
(params-updated? (mixer-new-params mix))
(mixer-new-mix! mix output)
(mixer-new-audio mix)
(vector-ref (mixer-new-slices mix) 0)
(f32vector-length (mixer-new-audio mix))
(f32slice-to-write (mixer-new-master-slice mix))
(f32slice-written (mixer-new-channel-slice mix 0))
(f32slice-written (mixer-new-channel-slice mix 1))
mix
