(import boar-mixer boar-noise boar-slice srfi-4)
(audio-start! SIO-0)
(define mm (mixer-from-lengths 4 2 1184))
(mixer-master-volume-set! mm 1.0)
(mixer-channel-volume-set! mm 0 0.7)
(mixer-channel-balance-set! mm 0 1 0.25)
(mixer-channel-balance-set! mm 0 0 0.75)
(define ch1-sl (mixer-channel->slice mm 0))
(define no (noise-from-length 1184))
(audio-data-set! SIO-0 mm)
(audio-f-set! SIO-0
  (lambda (u8 x n)
    (fill-white-noise! no)
    (f32slice-copy-from-f32vector ch1-sl (noise-white-f32 no))
    (mixer-mix! x u8)))
