(module matrix-1000 (note-on note-off)
  (import scheme (chicken base) (chicken type) srfi-4)

  (: note-on (fixnum -> (u8vector any -> fixnum)))
  (define (note-on n)
    (lambda (u8 x)
      (u8vector-set! u8 0 144)
      (u8vector-set! u8 1 n)
      (u8vector-set! u8 2 127)
      3))

  (: note-off (fixnum -> (u8vector any -> fixnum)))
  (define (note-off n)
    (lambda (u8 x)
      (u8vector-set! u8 0 144)
      (u8vector-set! u8 1 n)
      (u8vector-set! u8 2 0)
      3))
)
